export function parseYouTubeCountryCode(code: string): string {
  const c = code.toUpperCase();

  if (c === "US") return "United States";
  else if (c === "IN") return "India";
  else if (c === "BR") return "Brazil";
  else if (c === "GB" || c === "UK")
    return "United Kingdom"; // YT may return "GB"
  else if (c === "AR") return "Argentina";
  else if (c === "AU") return "Australia";
  else if (c === "AT") return "Austria";
  else if (c === "AZ") return "Azerbaijan";
  else if (c === "BD") return "Bangladesh";
  else if (c === "BY") return "Belarus";
  else if (c === "BE") return "Belgium";
  else if (c === "BO") return "Bolivia";
  else if (c === "BA") return "Bosnia and Herzegovina";
  else if (c === "BG") return "Bulgaria";
  else if (c === "KH") return "Cambodia";
  else if (c === "CM") return "Cameroon";
  else if (c === "CA") return "Canada";
  else if (c === "CL") return "Chile";
  else if (c === "CN") return "China";
  else if (c === "CO") return "Colombia";
  else if (c === "CR") return "Costa Rica";
  else if (c === "HR") return "Croatia";
  else if (c === "CU") return "Cuba";
  else if (c === "CZ") return "Czech Republic";
  else if (c === "DK") return "Denmark";
  else if (c === "DO") return "Dominican Republic";
  else if (c === "EC") return "Ecuador";
  else if (c === "EG") return "Egypt";
  else if (c === "SV") return "El Salvador";
  else if (c === "EE") return "Estonia";
  else if (c === "ET") return "Ethiopia";
  else if (c === "FI") return "Finland";
  else if (c === "FR") return "France";
  else if (c === "GE") return "Georgia";
  else if (c === "DE") return "Germany";
  else if (c === "GH") return "Ghana";
  else if (c === "GR") return "Greece";
  else if (c === "GT") return "Guatemala";
  else if (c === "HN") return "Honduras";
  else if (c === "HK") return "Hong Kong";
  else if (c === "HU") return "Hungary";
  else if (c === "IS") return "Iceland";
  else if (c === "ID") return "Indonesia";
  else if (c === "IR") return "Iran";
  else if (c === "IQ") return "Iraq";
  else if (c === "IE") return "Ireland";
  else if (c === "IL") return "Israel";
  else if (c === "IT") return "Italy";
  else if (c === "JM") return "Jamaica";
  else if (c === "JP") return "Japan";
  else if (c === "JO") return "Jordan";
  else if (c === "KZ") return "Kazakhstan";
  else if (c === "KE") return "Kenya";
  else if (c === "KW") return "Kuwait";
  else if (c === "LV") return "Latvia";
  else if (c === "LB") return "Lebanon";
  else if (c === "LY") return "Libya";
  else if (c === "LT") return "Lithuania";
  else if (c === "LU") return "Luxembourg";
  else if (c === "MY") return "Malaysia";
  else if (c === "MX") return "Mexico";
  else if (c === "MD") return "Moldova";
  else if (c === "MN") return "Mongolia";
  else if (c === "MA") return "Morocco";
  else if (c === "NP") return "Nepal";
  else if (c === "NL") return "Netherlands";
  else if (c === "NZ") return "New Zealand";
  else if (c === "NG") return "Nigeria";
  else if (c === "KP") return "North Korea";
  else if (c === "MK") return "North Macedonia";
  else if (c === "NO") return "Norway";
  else if (c === "PK") return "Pakistan";
  else if (c === "PA") return "Panama";
  else if (c === "PY") return "Paraguay";
  else if (c === "PE") return "Peru";
  else if (c === "PH") return "Philippines";
  else if (c === "PL") return "Poland";
  else if (c === "PT") return "Portugal";
  else if (c === "QA") return "Qatar";
  else if (c === "RO") return "Romania";
  else if (c === "RU") return "Russia";
  else if (c === "SA") return "Saudi Arabia";
  else if (c === "SN") return "Senegal";
  else if (c === "RS") return "Serbia";
  else if (c === "SG") return "Singapore";
  else if (c === "SK") return "Slovakia";
  else if (c === "SI") return "Slovenia";
  else if (c === "ZA") return "South Africa";
  else if (c === "KR") return "South Korea";
  else if (c === "ES") return "Spain";
  else if (c === "LK") return "Sri Lanka";
  else if (c === "SE") return "Sweden";
  else if (c === "CH") return "Switzerland";
  else if (c === "SY") return "Syria";
  else if (c === "TW") return "Taiwan";
  else if (c === "TZ") return "Tanzania";
  else if (c === "TH") return "Thailand";
  else if (c === "TN") return "Tunisia";
  else if (c === "TR") return "Turkey";
  else if (c === "UG") return "Uganda";
  else if (c === "UA") return "Ukraine";
  else if (c === "AE") return "United Arab Emirates";
  else if (c === "UY") return "Uruguay";
  else if (c === "VE") return "Venezuela";
  else if (c === "VN") return "Vietnam";
  else if (c === "YE") return "Yemen";
  else if (c === "ZM") return "Zambia";
  else if (c === "ZW") return "Zimbabwe";

  return "Other";
}
